export const formTransactions = {
  idTransaction: document.getElementById("InputId"),
  start_date: document.getElementById("start-date"),
  end_date: document.getElementById("end-date"),
  input_event: document.querySelector(".text-box"),
  getTransactionButton: document.querySelector(".get-button"),
  delete: document.querySelector(".delete-button"),
  aprove_delete: document.getElementById("deleteBtn"),
  cancel: document.getElementById("closeBtn"),
  create_transaction: document.getElementById("create-submit"),
  cancelTra: document.getElementById("closeBtnTra"),
  events: document.querySelector(".text-box").value,

  modalElement: document.getElementById("modal"),
  modalElementTr: document.getElementById("modalTransaction"),
  userIdElement: document.getElementById("user_id"),
  descriptionTextarea: document.querySelector(".description"),
  exit: document.getElementById("exist"),
  dropdown: document.querySelector(".dropdown"),
  option: document.querySelector(".option"),
  option1: document.querySelector(".option1"),
  dropdown1: document.querySelector(".dropdown1"),
  sumTransactionInput: document.getElementById("sumTransaction"),
  optionCat: document.getElementById("optionCat"),
  dropdownCat: document.getElementById("dropdownCat"),
  dateTransaction: document.getElementById("dateTr"),
  timeTransaction: document.getElementById("timeTr"),
  typeTransaction: document.querySelector(".radio"),
  catTransaction: document.querySelector(".categoryBox"),
  sumTransaction: document.getElementById("sumTransaction"),
  description: document.getElementById("descriptionTran"),
  createTra: document.getElementById("createTra"),
  editTransactionButton: document.getElementById("changeTra"),
  row: document.querySelector(".custom-table tbody"),
  radioButtons: document.querySelectorAll('input[name="typeTransaction"]'),

  showModalElementTr: document.getElementById("ShowModalTransaction"),
  showIdTransaction: document.getElementById("ShowInputId"),
  showDateTransaction: document.getElementById("ShowdateTr"),
  showTimeTransaction: document.getElementById("ShowtimeTr"),
  showCatTransaction: document.getElementById("showCatTran"),
  showSumTransaction: document.getElementById("ShowsumTransaction"),
  showDescription: document.getElementById("ShowdescriptionTran"),
  showCancelTra: document.getElementById("showCloseBtnTra"),

  labelMoreTransaction: document.getElementById("more"),

  buttonScanQr: document.getElementById("button_scan_qr"),
};
